name: Release ci

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  release-job:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - name: Checkout project
      uses: actions/checkout@v3
    - name: Install nodejs ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: echo "ok"
    - name: Install semantic
      run: |
        npm i -g semantic-release
        npm i -g @semantic-release/changelog
        npm i -g @semantic-release/github
        npm i -g @semantic-release/exec
        npm i -g @semantic-release/git
        npm i -g @semantic-release/release-notes-generator
    - name: Run semantic
      run: semantic-release --no-ci
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
